# Generated by Django 2.2 on 2020-02-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新时间'),
        ),
    ]
